# ABC Technologies - IT Consulting

## Task 1  

In [1]:
import numpy as np
HR=np.arange(3)

In [2]:
HR

array([0, 1, 2])

In [3]:
IT=np.arange(3,19)

In [4]:
IT

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [7]:
Finance=np.arange(19,24)

In [8]:
Finance

array([19, 20, 21, 22, 23])

In [6]:
Sales=np.arange(24,31)

In [9]:
Sales

array([24, 25, 26, 27, 28, 29, 30])

Conclusion - Created arrays of 30 candidates consist of four different departments.

## Task 2

In [10]:
HR_sal=([50,60,57])

In [21]:
IT_sal=([67])

In [12]:
Finance_sal=([60,65,50,70,87])

In [13]:
Sales_sal=([50,60,65,90,56,65,71])

In [16]:
HR_sal

[50, 60, 57]

In [35]:
IT_sal = np.array([67]*15)

In [36]:
IT_sal

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [18]:
Sales_sal

[50, 60, 65, 90, 56, 65, 71]

In [20]:
Finance_sal

[60, 65, 50, 70, 87]

Conclusion - Added the array of salaries of the employees for the four deparments 

## Task 3 

In [23]:
np.mean(HR_sal)

55.666666666666664

In [37]:
np.mean(IT_sal)

67.0

In [25]:
np.mean(Finance_sal)

66.4

In [26]:
np.mean(Sales_sal)

65.28571428571429

Conclusion - Found the department wise average salary.It is found that IT department has the highest average salary as 67.0

## Task 4

In [28]:
Highest_sal_HR = max(HR_sal)

In [29]:
Highest_sal_HR

60

In [30]:
Highest_sal_Finance = max(Finance_sal)

In [31]:
Highest_sal_Finance

87

Conclusion - The highest salaries in the HR department and Finance are found to be 60 and 87.

## Task 5 

In [38]:
IT_sal

array([67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67])

In [39]:
sum(IT_sal)

1005

In [44]:
bonus= IT_sal*(5/100)

In [45]:
bonus

array([3.35, 3.35, 3.35, 3.35, 3.35, 3.35, 3.35, 3.35, 3.35, 3.35, 3.35,
       3.35, 3.35, 3.35, 3.35])

In [46]:
Updated_salary =IT_sal + bonus

In [47]:
Updated_salary

array([70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35, 70.35,
       70.35, 70.35, 70.35, 70.35, 70.35, 70.35])

Conclusion - The updated salary after the 5% bonus for the IT department is found.