# Online shopping / E-Commerce Data Analysis

In [2]:
import numpy as np
from numpy import genfromtxt

In [3]:
shop_data=genfromtxt('DS1_C4_S1_Shopping_Data_Challenge.csv',delimiter=',',dtype=None,skip_header=1)

In [4]:
shop_data

array([[  1,  19,  15,  39],
       [  2,  21,  15,  81],
       [  3,  20,  16,   6],
       [  4,  23,  16,  77],
       [  5,  31,  17,  40],
       [  6,  22,  17,  76],
       [  7,  35,  18,   6],
       [  8,  23,  18,  94],
       [  9,  64,  19,   3],
       [ 10,  30,  19,  72],
       [ 11,  67,  19,  14],
       [ 12,  35,  19,  99],
       [ 13,  58,  20,  15],
       [ 14,  24,  20,  77],
       [ 15,  37,  20,  13],
       [ 16,  22,  20,  79],
       [ 17,  35,  21,  35],
       [ 18,  20,  21,  66],
       [ 19,  52,  23,  29],
       [ 20,  35,  23,  98],
       [ 21,  35,  24,  35],
       [ 22,  25,  24,  73],
       [ 23,  46,  25,   5],
       [ 24,  31,  25,  73],
       [ 25,  54,  28,  14],
       [ 26,  29,  28,  82],
       [ 27,  45,  28,  32],
       [ 28,  35,  28,  61],
       [ 29,  40,  29,  31],
       [ 30,  23,  29,  87],
       [ 31,  60,  30,   4],
       [ 32,  21,  30,  73],
       [ 33,  53,  33,   4],
       [ 34,  18,  33,  92],
       [ 35,  

# Task 1 

In [5]:
spending_score = shop_data[:,3]

In [6]:
spending_score

array([39, 81,  6, 77, 40, 76,  6, 94,  3, 72, 14, 99, 15, 77, 13, 79, 35,
       66, 29, 98, 35, 73,  5, 73, 14, 82, 32, 61, 31, 87,  4, 73,  4, 92,
       14, 81, 17, 73, 26, 75, 35, 92, 36, 61, 28, 65, 55, 47, 42, 42, 52,
       60, 54, 60, 45, 41, 50, 46, 51, 46, 56, 55, 52, 59, 51, 59, 50, 48,
       59, 47, 55, 42, 49, 56, 47, 54, 53, 48, 52, 42, 51, 55, 41, 44, 57,
       46, 58, 55, 60, 46, 55, 41, 49, 40, 42, 52, 47, 50, 42, 49, 41, 48,
       59, 55, 56, 42, 50, 46, 43, 48, 52, 54, 42, 46, 48, 50, 43, 59, 43,
       57, 56, 40, 58, 91, 29, 77, 35, 95, 11, 75,  9, 75, 34, 71,  5, 88,
        7, 73, 10, 72,  5, 93, 40, 87, 12, 97, 36, 74, 22, 90, 17, 88, 20,
       76, 16, 89,  1, 78,  1, 73, 35, 83,  5, 93, 26, 75, 20, 95, 27, 63,
       13, 75, 10, 92, 13, 86, 15, 69, 14, 90, 32, 86, 15, 88, 39, 97, 24,
       68, 17, 85, 23, 69,  8, 91, 16, 79, 28, 74, 18, 83])

In [7]:
greater_than_80= spending_score>80

In [8]:
greater_than_80

array([False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True,

In [9]:
filtered_op=spending_score[greater_than_80]

In [10]:
filtered_op

array([81, 94, 99, 98, 82, 87, 92, 81, 92, 91, 95, 88, 93, 87, 97, 90, 88,
       89, 83, 93, 95, 92, 86, 90, 86, 88, 97, 85, 91, 83])

In [11]:
count=len(filtered_op)

In [12]:
count

30

Conclusion - These are the details of the customer whose spending score is greater than 80.The count of it is 30

# Task 2 

In [13]:
age=shop_data[:,1]

In [14]:
age

array([19, 21, 20, 23, 31, 22, 35, 23, 64, 30, 67, 35, 58, 24, 37, 22, 35,
       20, 52, 35, 35, 25, 46, 31, 54, 29, 45, 35, 40, 23, 60, 21, 53, 18,
       49, 21, 42, 30, 36, 20, 65, 24, 48, 31, 49, 24, 50, 27, 29, 31, 49,
       33, 31, 59, 50, 47, 51, 69, 27, 53, 70, 19, 67, 54, 63, 18, 43, 68,
       19, 32, 70, 47, 60, 60, 59, 26, 45, 40, 23, 49, 57, 38, 67, 46, 21,
       48, 55, 22, 34, 50, 68, 18, 48, 40, 32, 24, 47, 27, 48, 20, 23, 49,
       67, 26, 49, 21, 66, 54, 68, 66, 65, 19, 38, 19, 18, 19, 63, 49, 51,
       50, 27, 38, 40, 39, 23, 31, 43, 40, 59, 38, 47, 39, 25, 31, 20, 29,
       44, 32, 19, 35, 57, 32, 28, 32, 25, 28, 48, 32, 34, 34, 43, 39, 44,
       38, 47, 27, 37, 30, 34, 30, 56, 29, 19, 31, 50, 36, 42, 33, 36, 32,
       40, 28, 36, 36, 52, 30, 58, 27, 59, 35, 37, 32, 46, 29, 41, 30, 54,
       28, 41, 36, 34, 32, 33, 38, 47, 35, 45, 32, 32, 30])

In [15]:
between_20_and_24 = (age >= 20) & (age <= 24)

In [16]:
between_20_and_24

array([False,  True,  True,  True, False,  True, False,  True, False,
       False, False, False, False,  True, False,  True, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False,  True,
       False, False, False,  True, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False,  True, False, False, False,
        True,  True, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False,

In [17]:
limit=age[between_20_and_24]

In [18]:
limit

array([21, 20, 23, 22, 23, 24, 22, 20, 23, 21, 21, 20, 24, 24, 23, 21, 22,
       24, 20, 23, 21, 23, 20])

In [19]:
filtered_data=shop_data[limit]

In [20]:
filtered_data

array([[22, 25, 24, 73],
       [21, 35, 24, 35],
       [24, 31, 25, 73],
       [23, 46, 25,  5],
       [24, 31, 25, 73],
       [25, 54, 28, 14],
       [23, 46, 25,  5],
       [21, 35, 24, 35],
       [24, 31, 25, 73],
       [22, 25, 24, 73],
       [22, 25, 24, 73],
       [21, 35, 24, 35],
       [25, 54, 28, 14],
       [25, 54, 28, 14],
       [24, 31, 25, 73],
       [22, 25, 24, 73],
       [23, 46, 25,  5],
       [25, 54, 28, 14],
       [21, 35, 24, 35],
       [24, 31, 25, 73],
       [22, 25, 24, 73],
       [24, 31, 25, 73],
       [21, 35, 24, 35]])

Conclusion - These are the customers whose age is inbetween 20 and 24

# Task 3

In [21]:
annual_income=shop_data[:,2]

In [22]:
annual_income

array([ 15,  15,  16,  16,  17,  17,  18,  18,  19,  19,  19,  19,  20,
        20,  20,  20,  21,  21,  23,  23,  24,  24,  25,  25,  28,  28,
        28,  28,  29,  29,  30,  30,  33,  33,  33,  33,  34,  34,  37,
        37,  38,  38,  39,  39,  39,  39,  40,  40,  40,  40,  42,  42,
        43,  43,  43,  43,  44,  44,  46,  46,  46,  46,  47,  47,  48,
        48,  48,  48,  48,  48,  49,  49,  50,  50,  54,  54,  54,  54,
        54,  54,  54,  54,  54,  54,  54,  54,  57,  57,  58,  58,  59,
        59,  60,  60,  60,  60,  60,  60,  61,  61,  62,  62,  62,  62,
        62,  62,  63,  63,  63,  63,  63,  63,  64,  64,  65,  65,  65,
        65,  67,  67,  67,  67,  69,  69,  70,  70,  71,  71,  71,  71,
        71,  71,  72,  72,  73,  73,  73,  73,  74,  74,  75,  75,  76,
        76,  77,  77,  77,  77,  78,  78,  78,  78,  78,  78,  78,  78,
        78,  78,  78,  78,  79,  79,  81,  81,  85,  85,  86,  86,  87,
        87,  87,  87,  87,  87,  88,  88,  88,  88,  93,  93,  9

In [23]:
maximum=max(annual_income)

In [24]:
maximum

137

In [25]:
minimum=min(annual_income)

In [26]:
minimum

15

In [27]:
a=shop_data[maximum]

In [28]:
b=shop_data[minimum]

In [29]:
a

array([138,  32,  73,  73])

In [30]:
b

array([16, 22, 20, 79])

Conclusion - These are the details of the customer with highest and lowest annual salary

# Task 4 

In [37]:
cust =np.where((shop_data[:,1]<45) & (shop_data[:,2]>35) & (shop_data[:,3]>75))

In [38]:
cust

(array([ 41, 123, 125, 127, 135, 141, 143, 145, 149, 151, 153, 155, 157,
        161, 163, 167, 173, 175, 179, 181, 183, 185, 189, 193, 195, 199],
       dtype=int64),)

In [39]:
customer = shop_data[cust]

In [40]:
customer

array([[ 42,  24,  38,  92],
       [124,  39,  69,  91],
       [126,  31,  70,  77],
       [128,  40,  71,  95],
       [136,  29,  73,  88],
       [142,  32,  75,  93],
       [144,  32,  76,  87],
       [146,  28,  77,  97],
       [150,  34,  78,  90],
       [152,  39,  78,  88],
       [154,  38,  78,  76],
       [156,  27,  78,  89],
       [158,  30,  78,  78],
       [162,  29,  79,  83],
       [164,  31,  81,  93],
       [168,  33,  86,  95],
       [174,  36,  87,  92],
       [176,  30,  88,  86],
       [180,  35,  93,  90],
       [182,  32,  97,  86],
       [184,  29,  98,  88],
       [186,  30,  99,  97],
       [190,  36, 103,  85],
       [194,  38, 113,  91],
       [196,  35, 120,  79],
       [200,  30, 137,  83]])

Conclusion - These are the detaills of customers who have age less than 45 , annual income greater than $35k and spending score greater than 75

# Task 5

In [42]:
coupon = np.random.randint(10,51,size=(200,1))

In [43]:
updated = np.append(shop_data,coupon,axis=1)

In [44]:
updated

array([[  1,  19,  15,  39,  10],
       [  2,  21,  15,  81,  49],
       [  3,  20,  16,   6,  11],
       [  4,  23,  16,  77,  46],
       [  5,  31,  17,  40,  40],
       [  6,  22,  17,  76,  34],
       [  7,  35,  18,   6,  26],
       [  8,  23,  18,  94,  11],
       [  9,  64,  19,   3,  31],
       [ 10,  30,  19,  72,  12],
       [ 11,  67,  19,  14,  15],
       [ 12,  35,  19,  99,  42],
       [ 13,  58,  20,  15,  48],
       [ 14,  24,  20,  77,  31],
       [ 15,  37,  20,  13,  33],
       [ 16,  22,  20,  79,  18],
       [ 17,  35,  21,  35,  33],
       [ 18,  20,  21,  66,  22],
       [ 19,  52,  23,  29,  44],
       [ 20,  35,  23,  98,  28],
       [ 21,  35,  24,  35,  39],
       [ 22,  25,  24,  73,  26],
       [ 23,  46,  25,   5,  21],
       [ 24,  31,  25,  73,  24],
       [ 25,  54,  28,  14,  24],
       [ 26,  29,  28,  82,  20],
       [ 27,  45,  28,  32,  21],
       [ 28,  35,  28,  61,  35],
       [ 29,  40,  29,  31,  50],
       [ 30,  

Conclusion - Added a new column to the data as a coupon for the coustumers ranges from $10 to $50 for all